terror: add stack trace in terror log
pingcap/parser pull request #989
Opened 2020-08-28 08:23 UTC by SunRunAway

### What problem does this PR solve? 

- None

### What is changed and how it works?

`terror.Log` can print stack trace for better debugging.
```
$ go test -check.f TestLog
[2020/08/28 16:23:23.840 +08:00] [ERROR] [terror.go:375] ["encountered error"] [error="xxx\ngithub.com/pingcap/errors.AddStack\n\t/Users/sunrunaway/go/pkg/mod/github.com/pingcap/errors@v0.11.4/errors.go:174\ngithub.com/pingcap/errors.Trace\n\t/Users/sunrunaway/go/pkg/mod/github.com/pingcap/errors@v0.11.4/juju_adaptor.go:15\ngithub.com/pingcap/parser/terror.Log\n\t/Users/sunrunaway/code/gopath/src/github.com/pingcap/parser/terror/terror.go:375\ngithub.com/pingcap/parser/terror.(*testTErrorSuite).TestLog\n\t/Users/sunrunaway/code/gopath/src/github.com/pingcap/parser/terror/terror_test.go:167\nreflect.Value.call\n\t/usr/local/Cellar/go@1.13/1.13.9/libexec/src/reflect/value.go:460\nreflect.Value.Call\n\t/usr/local/Cellar/go@1.13/1.13.9/libexec/src/reflect/value.go:321\ngithub.com/pingcap/check.(*suiteRunner).forkTest.func1\n\t/Users/sunrunaway/go/pkg/mod/github.com/pingcap/check@v0.0.0-20190102082844-67f458068fc8/check.go:836\ngithub.com/pingcap/check.(*suiteRunner).forkCall.func1\n\t/Users/sunrunaway/go/pkg/mod/github.com/pingcap/check@v0.0.0-20190102082844-67f458068fc8/check.go:730\nruntime.goexit\n\t/usr/local/Cellar/go@1.13/1.13.9/libexec/src/runtime/asm_amd64.s:1357"] [stack="github.com/pingcap/log.Error\n\t/Users/sunrunaway/go/pkg/mod/github.com/pingcap/log@v0.0.0-20191012051959-b742a5d432e9/global.go:42\ngithub.com/pingcap/parser/terror.Log\n\t/Users/sunrunaway/code/gopath/src/github.com/pingcap/parser/terror/terror.go:375\ngithub.com/pingcap/parser/terror.(*testTErrorSuite).TestLog\n\t/Users/sunrunaway/code/gopath/src/github.com/pingcap/parser/terror/terror_test.go:167\nreflect.Value.call\n\t/usr/local/Cellar/go@1.13/1.13.9/libexec/src/reflect/value.go:460\nreflect.Value.Call\n\t/usr/local/Cellar/go@1.13/1.13.9/libexec/src/reflect/value.go:321\ngithub.com/pingcap/check.(*suiteRunner).forkTest.func1\n\t/Users/sunrunaway/go/pkg/mod/github.com/pingcap/check@v0.0.0-20190102082844-67f458068fc8/check.go:836\ngithub.com/pingcap/check.(*suiteRunner).forkCall.func1\n\t/Users/sunrunaway/go/pkg/mod/github.com/pingcap/check@v0.0.0-20190102082844-67f458068fc8/check.go:730"]
PASS: terror_test.go:165: testTErrorSuite.TestLog	0.000s
```

### Check List 

Tests 

 
 - Manual test (add detailed scripts or steps below)
 
Related changes

 - Need to cherry-pick to the release branch

2020-08-28 08:32 UTC, tiancaiamao commented
LGTM

2020-08-28 08:33 UTC, bobotu reviewed
LGTM

2020-08-28 09:10 UTC, wjhuang2016 reviewed
LGTM

2020-08-28 09:17 UTC, bobotu commented
/merge

2020-08-28 09:18 UTC, kennytm requested changes
Use [`zap.Stack()`](https://pkg.go.dev/go.uber.org/zap/?tab=doc#Stack) if you want to log the stack trace, not like this please.

2020-08-28 09:21 UTC, kennytm approved these changes

2020-08-28 09:26 UTC, SunRunAway commented
/merge

2020-08-28 09:26 UTC, SunRunAway commented
@kennytm Please help merge

2020-08-28 10:12 UTC, merged

2020-08-31 03:51 UTC, tiancaiamao commented
By the way, the error stack should be printed, but after this PR https://github.com/pingcap/tidb/pull/12853
The `errorVerbose` is visible only when the log configure is set

```
[log]
enable-error-stack = true
```